const fs = require('fs');

const INPUT_FILE = 'flights.csv';
const WORKING_FILE = 'pending-flights.csv';

if (!fs.existsSync(INPUT_FILE)) {
  // Write input file if not exists
  fs.writeFileSync(INPUT_FILE, '#conf, fName, lName\n');
}

if (!fs.existsSync(WORKING_FILE)) {
  // Write input file if not exists
  fs.writeFileSync(WORKING_FILE, '#DO NOT EDIT THIS FILE\n#conf, fName, lName\n');
}

// Read our input file
var contents = readFileNoComments(INPUT_FILE)
  .reduce(function(line, arr) {
    var parts = line.split(',');
    arr.push({
      conf: parts[0],
      fName: parts[1],
      lName: parts[2],
    });

    return arr;
  }, []);

  
  //https://www.southwest.com/flight/lookup-air-reservation.html?default=cc



function readFileNoComments(filename) {
  return fs.readFileSync(filename)
  .split('\n')
  .filter(function(line) {
    // Filter comments
    return line.trim().charAt(0) !== '#';
  });
}


function readFile(filename) {
  return new Promise(function(resolve, reject) {
    fs.readFile(filename, funtion(err, data) {
      if (err) {
        reject(err);
      } else {
        resolve(data);
      }
    });
  });
}
